### ISSUE TITLE
outdated version

### ISSUE THREAD

**Issue by flomine** [YunoHost-Apps/gitea_ynh#115]
### Describe the bug
shipped version is 1.22.3 while current upstream version is 1.22.6.
The gitea version in yunohost is outdated and may present a security risk.

### Expected behavior
provide an updated version

**Comment by Josue-T** [comment]
Ok thanks for the feedback. Seem that the auto update system is broken. @alexAubin, @Salamandar  do you have any idea why this app don't have the auto update PR ?

**Comment by Josue-T** [comment]
Fixed by #117
