### ISSUE TITLE
Gitea 1.8.1

### ISSUE THREAD

**Issue by rushsteve1** [YunoHost-Apps/gitea_ynh#13]
Gitea [1.8.0](https://blog.gitea.io/2019/04/gitea-1.8.0-is-released/) and [1.8.1](https://blog.gitea.io/2019/05/gitea-1.8.1-is-released/) have been out for a while now and the YunoHost version needs to be updated.

**Comment by Josue-T** [comment]
Hello,

A testing release is available here : https://framagit.org/YunoHost-Apps/gitea_ynh/merge_requests/39

Can you also open your PR here : https://framagit.org/YunoHost-Apps/gitea_ynh/issues as explained [here](https://github.com/YunoHost-Apps/gitea_ynh/issues/9)

**Comment by rushsteve1** [comment]
@Josue-T Wow thanks for the quick reply. I see things have been moved to FramaGit good to know, sorry to bother you.
