### ISSUE TITLE
Upgrade to latest version (v1.11.1)

### ISSUE THREAD

**Issue by ahstro** [YunoHost-Apps/gitea_ynh#15]
Latest version of Gitea (as of writing) is [v1.11.1](https://github.com/go-gitea/gitea/releases/tag/v1.11.1), but this package is still at v1.10.1 😊

**Comment by Josue-T** [comment]
Hello,

This repository is **only** a miror of the official repository [here](https://framagit.org/YunoHost-Apps/gitea_ynh).

And there are already a pull request with this version [here](https://framagit.org/YunoHost-Apps/gitea_ynh/-/merge_requests/51)
