### ISSUE TITLE
503 after upgrade

### ISSUE THREAD

**Issue by kay0u** [YunoHost-Apps/gitea_ynh#19]
Hi!

After upgrade from 1.11.6 to 1.12.2, I got a 503 error [with in gitea.log](https://paste.yunohost.org/ezuzogawuz.pas)

I fixed it by following [this issue](https://github.com/go-gitea/gitea/issues/9347#issuecomment-633406566)

`sudo -u gitea /opt/gitea/gitea convert`

**Comment by pbeliveau** [comment]
Same fix but could not do so from `sudo -u`
I had to drop in gitea user to run the command:

```bash
sudo su gitea
cd /opt/gitea/
./gitea convert
```

**Comment by Josue-T** [comment]
Closing as it look pretty old
