### ISSUE TITLE
Fix Readme

### ISSUE THREAD

**Issue by Zykino** [YunoHost-Apps/gitea_ynh#2]
Image / links to "Integration level" and "Build Status" are broken.

If I click on the image "Install with Yunohost" I'm redirected to a page stating that the app is neither maintained officially or by the community.

This makes me wondering: Can I install this app yet?
Also there are some issues/PR over https://github.com/Bridouz/gitea_ynh/issues, are they resolved here of should we re-open them to track them?

**Comment by Rafi594** [comment]
Yes because this app is not finished yet I have not added it to the application list. But I'm working on it right now

**Comment by Kcchouette** [comment]
@Rafi594 Can you add it on https://ci-apps.yunohost.org/jenkins/ please?

**Comment by Rafi594** [comment]
Migrated to Framagit https://framagit.org/YunoHost-Apps/gitea_ynh/issues/2
You can login with your GitHub account

**Comment by Josue-T** [comment]
Probably fixed
