### ISSUE TITLE
ARM64 version

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/gitea_ynh#21]
After an update, i get : 
```
Warning: Dec 02 23:31:32 salamandar.fr systemd[14418]: gitea.service: Failed to execute command: Exec format error
Warning: Dec 02 23:31:32 salamandar.fr systemd[14418]: gitea.service: Failed at step EXEC spawning /opt/gitea/gitea: Exec format error
```
I downloaded the arm64 version of Gitea (https://github.com/go-gitea/gitea/releases/download/v1.13.0/gitea-1.13.0-linux-arm64) and now that works correctly. Also, looks like there isn't any arm64 flavour in the config/ directory of gitea_ynh.

**Comment by Josue-T** [comment]
Should be fixed in the testing
