### ISSUE TITLE
Problem after upgrade

### ISSUE THREAD

**Issue by bugsysop** [YunoHost-Apps/gitea_ynh#24]
After an upgrade to the last version (with Yunohost up to date version):

```
2021/03/06 17:13:07 routers/init.go:88:initDBEngine() [E] ORM engine initialization attempt #2/10 failed. Error: migrate: do migrate: Sync2: Error 1118: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```

Visiting Gitea home Page give now a `502 Bad Gateway`

**Comment by bugsysop** [comment]
Reversed to previous version (from backup): Gitea wiking fine

**Comment by Josue-T** [comment]
Duplicate: https://framagit.org/YunoHost-Apps/gitea_ynh/-/issues/37

**Comment by bugsysop** [comment]
I'm sorry, but we're on **GitHub** how am I supposed to know that there's an open ticket on Framagit?
