### ISSUE TITLE
/home/$app directory not deleted during app removal

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/gitea_ynh#26]
"Transfer" from @Nochalek's issue at https://github.com/YunoHost/issues/issues/1789

> The directory is in /home/gitea
and when you try to install gitea again, it makes another gitea folder.

It seems `$app` user homedir is indeed set in `/home` (cf. [this line](https://github.com/YunoHost-Apps/gitea_ynh/blob/001c90e051899c9abfd3ed8decd8f8734625bc86/scripts/install#L68)).

(I do not know specifics about Gitea, but usually user app homedirs are under `/home/yunohost.app/$app`.)

**Comment by Josue-T** [comment]
Cf https://framagit.org/YunoHost-Apps/gitea_ynh#remove

**Comment by tituspijean** [comment]
Closing, as it is intended behaviour.
