### ISSUE TITLE
I can't install, infinite loop

### ISSUE THREAD

**Issue by Sysdraw** [YunoHost-Apps/gitea_ynh#37]
### Describe the bug

I have an infinite loop when I run the Gitea installer.

### Context

- Hardware: *VPS*
- YunoHost version: *4.3.5*
- I have access to my server: *Through SSH &&  through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: stable

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install gitea --debug
    ```
### Expected behavior

The expected behaviour is the program can install all the requirements without infinite loop without error.

### Logs

You can see the logs [here](https://paste.yunohost.org/raw/eranogubuf)

**Comment by Josue-T** [comment]
Closing as it's pretty old. Please reopen if the issue persist.
