### ISSUE TITLE
Installation failed (Yunohost 3)

### ISSUE THREAD

**Issue by Bridouz** [YunoHost-Apps/gitea_ynh#4]
Installation fails :

```
Warning: cp: cannot stat '../conf/app.ini': No such file or directory
```

**Comment by Rafi594** [comment]
Normally fixed by https://github.com/YunoHost-Apps/gitea_ynh/commit/4233531503297b83825e654dd3818df0860e6963

**Comment by wyllyjon** [comment]
Hello ! 

I have the problem right now :
``Warning: Created symlink from /etc/systemd/system/multi-user.target.wants/gitea.service to /etc/systemd/system/gitea.service.
Warning: cp: cannot stat ‘/opt/gitea/app.ini’: No such file or directory
Warning: !!
Warning:   gitea's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Warning: Remove the user gitea
Warning: Removed symlink /etc/systemd/system/multi-user.target.wants/gitea.service.
Warning: Unknown service 'gitea'
Warning: gitea has not been properly removed
Success! The SSOwat configuration has been generated
Error: Installation failed``

**Comment by Rafi594** [comment]
Fixed by https://github.com/YunoHost-Apps/gitea_ynh/commit/349992d4f3921e4e1adb37a0cace4a5a9eb67099
