### ISSUE TITLE
Wrong readme instruction lead to unusable ssh

### ISSUE THREAD

**Issue by narduin** [YunoHost-Apps/gitea_ynh#42]
### Describe the bug

After a clean install following the official Readme here, it was impossible to use ssh to pull/push.
It kept asking for gitea's password.
After reinstalling, trying the testing branch and several hours of tests, I found [a comment](https://framagit.org/YunoHost-Apps/gitea_ynh/-/issues/18#note_707336) on the gitlab repo that it could be coming from
```
UsePAM no
```
So I changed it to `yes` and now I can ssh with gitea.
I don't know if it's coming from my install or if it's an error in the Readme.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master/testing

### Steps to reproduce

- Install master or testing (web interface or command line)
- Add `gitea` user to `ssh.app` group
- Edit `sshd_config` to match the one described in the Readme
- Add an SSH key to your profile in gitea app
- Try to push a repo

### Expected behavior

Should be able to push without being asked for a password using SSH.

**Comment by Zykino** [comment]
Thanks, as admin `sudo usermod -a -G ssh.app gitea` was necessary. Nothing was needed to change in the `/etc/ssh/sshd_config` file in the end.

**Comment by Josue-T** [comment]
Closing as there was a lot of change on the doc since this. Please reopen if there still need a fix on the doc.
