### ISSUE TITLE
Make LFS usage configurable

### ISSUE THREAD

**Issue by ndarilek** [YunoHost-Apps/gitea_ynh#47]
Hello,

I use git-lfs in multiple Gitea installations. Unfortunately, it's a bit of a pain to upgrade Gitea, stop the service (not sure if that's necessary but I do it anyway), read up on where the LFS keys go, re-add them to the configuration, and restart. Rinse and repeat for 2-3 instances.

How hard would it be to add an LFS-enabled configuration key that outputs the LFS configuration if set to true? If it makes things easier, I don't even care if it isn't in the UI. I'd just like to not have to repeat this configuration for each of multiple upgrades.

Thanks.

**Comment by Josue-T** [comment]
Hello,

Can you provide a configuration that we can use. If it's easy to implement it would be good to enable it by default.
And it would be really nice if you can make a pull request to add this new feature.

Best regards

Josué

**Comment by Josue-T** [comment]
Hello,

Can you provide a configuration that we can use. If it's easy to implement it would be good to enable it by default.
And it would be really nice if you can make a pull request to add this new feature.

Best regards

Josué

**Comment by ndarilek** [comment]
There's an example config in the README.md:

To use a repository with an LFS setup, you need to activate-it on /opt/gitea/custom/conf/app.ini
[server]
LFS_START_SERVER = true
LFS_HTTP_AUTH_EXPIRY = 20m
By default Nginx is setup with a max value to updload files at 200 Mo. It's possible to change this value on /etc/nginx/conf.d/my.domain.tld.d/gitea.conf.
client_max_body_size 200M;
Don't forget to restart Gitea sudo systemctl restart gitea.service.
This settings are restored to the default config when Gitea is updated. Don't forget to restore your setup after all updates.

**Comment by Josue-T** [comment]
Fixed by #50
