### ISSUE TITLE
Can't access Admin Panel

### ISSUE THREAD

**Issue by aroooo** [YunoHost-Apps/gitea_ynh#54]
### Describe the bug

*When accessing domain.tld/gitea/admin, the page responds with ```Forbidden```.*
Moreover, I wasn't handed the Admin Token when the install finished...

### Context

- Hardware: *Raspberry Pi (3B+) at home*
- YunoHost version: 11.0.9.12
- I have access to my server: *Through SSH via Windows*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: https://github.com/YunoHost-Apps/gitea_ynh/

### Steps to reproduce

```yunohost app install -a path=/git -l Gitea gitea```
> Connect through SSO
> Head to domain.tld/gitea/admin
> Get rejected

### Expected behavior

*Should be able to get to the Admin Panel.*

### Logs
None

Thank you!

**Comment by tajmone** [comment]
@ineanto: 

> and creating a temporary admin user using Gitea's CLI

Could you pleas tell me how to access the Gitea CLI? 

I've tried the `gitea` command after logging as root via SSH, but the shell tells me that the command doesn't exist...

Unfortunately I couldn't work out more details from the official Gitea docs (according to these, the command should be available, but apparently it isn't).

Thanks!

**Comment by stilobique** [comment]
I think the package need to be updated to select the admin user with the install.

Before to create your admin user, call your admin right `sudo su`, and change your working directory to where the app are installed `/home/yunohost.app/gitea`.
