### ISSUE TITLE
Uploading Files to YNH Gitea - Conflicting & Unclear How to Fix

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [YunoHost-Apps/gitea_ynh#58]
1.
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
Issue opened b/c I came across conflicting solutions.

2.
### Describe the bug
a) Web interface does not have a "Upload Files" to the new repo button, however several web sources mention this . Does this exist? it's unclear. Can local files be uploaded through web interface?
b) Git push also does not work (Install option as Public per Gitea docs)
I initialize, add & commit my local folder. I then
`git remote add origin ssh://git@gitea.<domain>/gitea/<user>/<repo>`
`git push -u origin master`
I get: `error: src refspec master does not match any
error: failed to push some refs to 'ssh://<domain>/gitea/<user>/<repo>`

3.
I looked through `/etc/yunohost/apps/gitea/conf/app.ini` for some clues to enable features but I chose not to break something that is semi-working. If there's a config option to resolve this that would be great!

So I'm at a loss on how to upload files & code to my YNH Gitea repos.

### Context
- Hardware: on-prem x64, YNH  11.0.9.14
- YunoHost version: Gitea Version: 1.17.2
- I have access to my server: Any / All
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: NO
- Using, or trying to install package version/branch: Gitea Version: 1.17.2
- If upgrading, current package version: N/A

### Logs
N/A

**Comment by tituspijean** [comment]
2.b. : are you sure the repository has a `master` branch, not one called `main`?

**Comment by Josue-T** [comment]
Closing as it's pretty old. Please reopen if you problem persist.
