### ISSUE TITLE
Other ssh port

### ISSUE THREAD

**Issue by Pypypierre** [YunoHost-Apps/gitea_ynh#65]
I tried to change the ssh port, and it works, I can push, pull... But my problem is that when I try to paste the clone url, I had something like this: gitea@domain.fr:test/test.git but it doesn't work. I found this command and it works: gitea@domain.fr:3000/test/test.git but the url is never updated in the correct form.

I have been looking for solutions, but my research has led me nowhere so here I am, thank you for your time.

**Comment by Josue-T** [comment]
Hello,

To fix the configuration of gitea with the new port that you set, you need to do a force upgrade of gitea. The app will retrive the new ssh port and update correctly the configuration.

**Comment by Pypypierre** [comment]
It's works thx
