### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/gitea_ynh#7]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/gitea%20(Community)/13/consoleFull

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by Rafi594** [comment]
Fixed by https://github.com/YunoHost-Apps/gitea_ynh/commit/349992d4f3921e4e1adb37a0cace4a5a9eb67099
