### ISSUE TITLE
Restoration fails - missing directory

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/gitea_ynh#82]
### Describe the bug
Restoration of a working app on a new server fails, with the message :
" WARNING - chown: cannot access '/home/yunohost.app/gitea': No such file or directory "
No special operation made, I was just testing the app...
Thanks for your input/help to fix the package !

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.3
- I have access to my server: *Through SSH, and through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

    ```sh
    sudo yunohost backup restore my_backup --apps gitea
    ```

### Expected behavior

Restoration should cmplete and the appa available on the new server.

### Logs
see : https://paste.yunohost.org/raw/upuyimetit

**Comment by Josue-T** [comment]
Sorry I'm closing as there was a lot of change since this. Please reopen if the issue persist.

**Comment by Jaxom99** [comment]
It's OK to do some cleaning, I did not test this again. Thanks for taking care of this app :+1:
